version: "3.9"

services:
  citynet-fe-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: citynet-fe-dev
    ports:
      - "5173:5173"   
    volumes:
      - .:/app        # mount project lokal -> container (supaya hot reload jalan)
      - /app/node_modules  # jangan overwrite node_modules
    environment:
      - NODE_ENV=development
